name: 报告新的学校
description: 报告新的学校
labels: ["campus"]
body:
  - type: input
    id: author
    attributes:
      label: 贡献者名称
      description: 填写你期望的名称。如不希望署名，请填“匿名”
    validations:
      required: true
  - type: markdown
    attributes:
      value: 感谢您的报告，请根据该表单填充必要信息。
  - type: input
    id: campus-name
    attributes:
      label: 学校名称
      description: 该学校的名字全称
    validations:
      required: true
  - type: input
    id: address
    attributes:
      label: 地址位置
      description: 该学校的地理位置
    validations:
      required: true
  - type: markdown
    attributes:
      value: 下面是一些基本生活信息，你可以说有、没有、不了解、部分情况下有（如只有某校区有独立卫浴、医保限部分医院报销、医保转诊才能报销）
  - type: input
    id: bathroom-dormitory
    attributes:
      label: 宿舍独立卫浴
      description: 宿舍独立卫生间或者独立浴室的情况，公共澡堂可以讲讲私密度情况
  - type: input
    id: bathroom-genderless
    attributes:
      label: 教学区第三卫生间
  - type: input
    id: exemption-military-training
    attributes:
      label: 军训减免
      description: 协商减免，凭医学材料减免
  - type: input
    id: exemption-hair
    attributes:
      label: 军训管不管头发
  - type: input
    id: exemption-sports
    attributes:
      label: 体育减免
      description: 协商减免，凭医学材料减免
  - type: input
    id: medicare
    attributes:
      label: 医保的可用情况
  - type: input
    id: xiaoyiyuan
    attributes:
      label: 校医院可用度
      description: 能不能进行激素检查，能不能开到激素药
  - type: textarea
    id: general
    attributes:
      label: 现状梗概
      description: 您在学校就读时遭遇的问题，或有补充的信息，对于 MtF 不方便的地方请指出
  - type: checkboxes
    id: license
    attributes:
      label: 以 CC-BY-SA 4.0 协议分发
      description: 本站采用 [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.zh-Hans) 协议分发内容
      options:
        - label: 我同意以 CC-BY-SA 4.0 协议分发
          required: true
