/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearanceToggle: typeof import('./../../packages/vitepress-theme-project-trans/dist/components/AppearanceToggle.vue')['default']
    AppFooter: typeof import('./../../packages/vitepress-theme-project-trans/dist/components/AppFooter.vue')['default']
    AppSBox: typeof import('./../../packages/vitepress-theme-project-trans/dist/components/AppSBox.vue')['default']
    ArticlesMenu: typeof import('./../../packages/vitepress-theme-project-trans/dist/components/ArticlesMenu.vue')['default']
    CopyrightInfo: typeof import('./../../packages/vitepress-theme-project-trans/dist/components/CopyrightInfo.vue')['default']
    HomeContent: typeof import('./../../packages/vitepress-theme-project-trans/dist/components/HomeContent.vue')['default']
    PageInfo: typeof import('./../../packages/vitepress-theme-project-trans/dist/components/PageInfo.vue')['default']
  }
}
