/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppearanceToggle: typeof import('./theme/components/AppearanceToggle.vue')['default']
    Changelog: typeof import('./theme/components/Changelog.vue')['default']
    HomeContent: typeof import('./theme/components/HomeContent.vue')['default']
    PageInfo: typeof import('./theme/components/PageInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
