name: Run markdownlint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths: ['**/*.md']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: npx markdownlint-cli "**/*.md" --ignore "docs/index.md"
