name: 测试

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
